set(lib_name core)
#######################################
# library sources
set(thisfile ${wxroot}/build/cmake/${lib_name}.cmake)
source_group("" FILES ${thisfile})
list(APPEND ${lib_name}_libsrcs ${thisfile})
########################
# Common Headers
set(Common_hdrs
  ${wxroot}/include/wx/accel.h
  ${wxroot}/include/wx/access.h
  ${wxroot}/include/wx/affinematrix2d.h
  ${wxroot}/include/wx/affinematrix2dbase.h
  ${wxroot}/include/wx/anidecod.h
  ${wxroot}/include/wx/animdecod.h
  ${wxroot}/include/wx/anybutton.h
  ${wxroot}/include/wx/appprogress.h
  ${wxroot}/include/wx/artprov.h
  ${wxroot}/include/wx/bitmap.h
  ${wxroot}/include/wx/bmpbuttn.h
  ${wxroot}/include/wx/bookctrl.h
  ${wxroot}/include/wx/persist/bookctrl.h
  ${wxroot}/include/wx/brush.h
  ${wxroot}/include/wx/busyinfo.h
  ${wxroot}/include/wx/button.h
  ${wxroot}/include/wx/caret.h
  ${wxroot}/include/wx/checkbox.h
  ${wxroot}/include/wx/checklst.h
  ${wxroot}/include/wx/choicdlg.h
  ${wxroot}/include/wx/choice.h
  ${wxroot}/include/wx/choicebk.h
  ${wxroot}/include/wx/clipbrd.h
  ${wxroot}/include/wx/clrpicker.h
  ${wxroot}/include/wx/cmdproc.h
  ${wxroot}/include/wx/cmndata.h
  ${wxroot}/include/wx/collheaderctrl.h
  ${wxroot}/include/wx/collpane.h
  ${wxroot}/include/wx/colordlg.h
  ${wxroot}/include/wx/colour.h
  ${wxroot}/include/wx/colourdata.h
  ${wxroot}/include/wx/combo.h
  ${wxroot}/include/wx/combobox.h
  ${wxroot}/include/wx/compositewin.h
  ${wxroot}/include/wx/control.h
  ${wxroot}/include/wx/cshelp.h
  ${wxroot}/include/wx/ctrlsub.h
  ${wxroot}/include/wx/cursor.h
  ${wxroot}/include/wx/custombgwin.h
  ${wxroot}/include/wx/dataobj.h
  ${wxroot}/include/wx/dc.h
  ${wxroot}/include/wx/dcclient.h
  ${wxroot}/include/wx/dcgraph.h
  ${wxroot}/include/wx/dcmemory.h
  ${wxroot}/include/wx/dcmirror.h
  ${wxroot}/include/wx/dcprint.h
  ${wxroot}/include/wx/dcps.h
  ${wxroot}/include/wx/dcscreen.h
  ${wxroot}/include/wx/dcsvg.h
  ${wxroot}/include/wx/dialog.h
  ${wxroot}/include/wx/dialup.h
  ${wxroot}/include/wx/dirctrl.h
  ${wxroot}/include/wx/dirdlg.h
  ${wxroot}/include/wx/display.h
  ${wxroot}/include/wx/display_impl.h
  ${wxroot}/include/wx/dnd.h
  ${wxroot}/include/wx/docmdi.h
  ${wxroot}/include/wx/docview.h
  ${wxroot}/include/wx/dragimag.h
  ${wxroot}/include/wx/effects.h
  ${wxroot}/include/wx/encinfo.h
  ${wxroot}/include/wx/evtloopsrc.h
  ${wxroot}/include/wx/fdrepdlg.h
  ${wxroot}/include/wx/filectrl.h
  ${wxroot}/include/wx/filedlg.h
  ${wxroot}/include/wx/filehistory.h
  ${wxroot}/include/wx/filepicker.h
  ${wxroot}/include/wx/fmappriv.h
  ${wxroot}/include/wx/font.h
  ${wxroot}/include/wx/fontdata.h
  ${wxroot}/include/wx/fontdlg.h
  ${wxroot}/include/wx/fontenum.h
  ${wxroot}/include/wx/fontpicker.h
  ${wxroot}/include/wx/fontutil.h
  ${wxroot}/include/wx/frame.h
  ${wxroot}/include/wx/gauge.h
  ${wxroot}/include/wx/gbsizer.h
  ${wxroot}/include/wx/gdicmn.h
  ${wxroot}/include/wx/gdiobj.h
  ${wxroot}/include/wx/geometry.h
  ${wxroot}/include/wx/gifdecod.h
  ${wxroot}/include/wx/graphics.h
  ${wxroot}/include/wx/headercol.h
  ${wxroot}/include/wx/headerctrl.h
  ${wxroot}/include/wx/help.h
  ${wxroot}/include/wx/helpbase.h
  ${wxroot}/include/wx/helphtml.h
  ${wxroot}/include/wx/helpwin.h
  ${wxroot}/include/wx/icon.h
  ${wxroot}/include/wx/iconbndl.h
  ${wxroot}/include/wx/imagbmp.h
  ${wxroot}/include/wx/image.h
  ${wxroot}/include/wx/imaggif.h
  ${wxroot}/include/wx/imagiff.h
  ${wxroot}/include/wx/imagjpeg.h
  ${wxroot}/include/wx/imaglist.h
  ${wxroot}/include/wx/imagpcx.h
  ${wxroot}/include/wx/imagpng.h
  ${wxroot}/include/wx/imagpnm.h
  ${wxroot}/include/wx/imagtga.h
  ${wxroot}/include/wx/imagtiff.h
  ${wxroot}/include/wx/imagxpm.h
  ${wxroot}/include/wx/infobar.h
  ${wxroot}/include/wx/itemid.h
  ${wxroot}/include/wx/layout.h
  ${wxroot}/include/wx/listbase.h
  ${wxroot}/include/wx/listbook.h
  ${wxroot}/include/wx/listbox.h
  ${wxroot}/include/wx/listctrl.h
  ${wxroot}/include/wx/matrix.h
  ${wxroot}/include/wx/mdi.h
  ${wxroot}/include/wx/menu.h
  ${wxroot}/include/wx/menuitem.h
  ${wxroot}/include/wx/metafile.h
  ${wxroot}/include/wx/minifram.h
  ${wxroot}/include/wx/modalhook.h
  ${wxroot}/include/wx/mousemanager.h
  ${wxroot}/include/wx/msgdlg.h
  ${wxroot}/include/wx/nativewin.h
  ${wxroot}/include/wx/nonownedwnd.h
  ${wxroot}/include/wx/notebook.h
  ${wxroot}/include/wx/numdlg.h
  ${wxroot}/include/wx/overlay.h
  ${wxroot}/include/wx/ownerdrw.h
  ${wxroot}/include/wx/palette.h
  ${wxroot}/include/wx/panel.h
  ${wxroot}/include/wx/paper.h
  ${wxroot}/include/wx/pen.h
  ${wxroot}/include/wx/persist.h
  ${wxroot}/include/wx/pickerbase.h
  ${wxroot}/include/wx/popupwin.h
  ${wxroot}/include/wx/position.h
  ${wxroot}/include/wx/preferences.h
  ${wxroot}/include/wx/print.h
  ${wxroot}/include/wx/printdlg.h
  ${wxroot}/include/wx/prntbase.h
  ${wxroot}/include/wx/progdlg.h
  ${wxroot}/include/wx/quantize.h
  ${wxroot}/include/wx/radiobox.h
  ${wxroot}/include/wx/radiobut.h
  ${wxroot}/include/wx/range.h
  ${wxroot}/include/wx/rawbmp.h
  ${wxroot}/include/wx/rearrangectrl.h
  ${wxroot}/include/wx/region.h
  ${wxroot}/include/wx/renderer.h
  ${wxroot}/include/wx/richmsgdlg.h
  ${wxroot}/include/wx/scopeguard.h
  ${wxroot}/include/wx/scrolbar.h
  ${wxroot}/include/wx/scrolwin.h
  ${wxroot}/include/wx/selstore.h
  ${wxroot}/include/wx/settings.h
  ${wxroot}/include/wx/simplebook.h
  ${wxroot}/include/wx/sizer.h
  ${wxroot}/include/wx/slider.h
  ${wxroot}/include/wx/spinbutt.h
  ${wxroot}/include/wx/spinctrl.h
  ${wxroot}/include/wx/persist/splitter.h
  ${wxroot}/include/wx/splitter.h
  ${wxroot}/include/wx/srchctrl.h
  ${wxroot}/include/wx/statbmp.h
  ${wxroot}/include/wx/statbox.h
  ${wxroot}/include/wx/statline.h
  ${wxroot}/include/wx/stattext.h
  ${wxroot}/include/wx/statusbr.h
  ${wxroot}/include/wx/systhemectrl.h
  ${wxroot}/include/wx/taskbarbutton.h
  ${wxroot}/include/wx/tbarbase.h
  ${wxroot}/include/wx/testing.h
  ${wxroot}/include/wx/textcompleter.h
  ${wxroot}/include/wx/textctrl.h
  ${wxroot}/include/wx/textdlg.h
  ${wxroot}/include/wx/textentry.h
  ${wxroot}/include/wx/textwrapper.h
  ${wxroot}/include/wx/tglbtn.h
  ${wxroot}/include/wx/tipwin.h
  ${wxroot}/include/wx/toolbar.h
  ${wxroot}/include/wx/toolbook.h
  ${wxroot}/include/wx/tooltip.h
  ${wxroot}/include/wx/persist/toplevel.h
  ${wxroot}/include/wx/toplevel.h
  ${wxroot}/include/wx/treebase.h
  ${wxroot}/include/wx/persist/treebook.h
  ${wxroot}/include/wx/treebook.h
  ${wxroot}/include/wx/treectrl.h
  ${wxroot}/include/wx/uiaction.h
  ${wxroot}/include/wx/valgen.h
  ${wxroot}/include/wx/validate.h
  ${wxroot}/include/wx/valnum.h
  ${wxroot}/include/wx/valtext.h
  ${wxroot}/include/wx/vidmode.h
  ${wxroot}/include/wx/vlbox.h
  ${wxroot}/include/wx/vms_x_fix.h
  ${wxroot}/include/wx/vscroll.h
  ${wxroot}/include/wx/persist/window.h
  ${wxroot}/include/wx/window.h
  ${wxroot}/include/wx/windowid.h
  ${wxroot}/include/wx/windowptr.h
  ${wxroot}/include/wx/withimages.h
  ${wxroot}/include/wx/wrapsizer.h
  ${wxroot}/include/wx/wupdlock.h
  ${wxroot}/include/wx/xrc/xmlreshandler.h
  ${wxroot}/include/wx/xpmdecod.h
  ${wxroot}/include/wx/xpmhand.h
  )
source_group("Common Headers" FILES ${Common_hdrs})
list(APPEND ${lib_name}_libsrcs ${Common_hdrs})
########################
# Common Sources
set(Common_srcs
  ${wxroot}/src/common/accelcmn.cpp
  ${wxroot}/src/common/accesscmn.cpp
  ${wxroot}/src/common/affinematrix2d.cpp
  ${wxroot}/src/common/anidecod.cpp
  ${wxroot}/src/common/appcmn.cpp
  ${wxroot}/src/common/artprov.cpp
  ${wxroot}/src/common/artstd.cpp
  ${wxroot}/src/common/arttango.cpp
  ${wxroot}/src/common/bmpbase.cpp
  ${wxroot}/src/common/bmpbtncmn.cpp
  ${wxroot}/src/common/bookctrl.cpp
  ${wxroot}/src/common/btncmn.cpp
  ${wxroot}/src/common/cairo.cpp
  ${wxroot}/src/common/checkboxcmn.cpp
  ${wxroot}/src/common/checklstcmn.cpp
  ${wxroot}/src/common/choiccmn.cpp
  ${wxroot}/src/common/clipcmn.cpp
  ${wxroot}/src/common/clrpickercmn.cpp
  ${wxroot}/src/common/cmdproc.cpp
  ${wxroot}/src/common/cmndata.cpp
  ${wxroot}/src/common/colourcmn.cpp
  ${wxroot}/src/common/colourdata.cpp
  ${wxroot}/src/common/combocmn.cpp
  ${wxroot}/src/common/containr.cpp
  ${wxroot}/src/common/cshelp.cpp
  ${wxroot}/src/common/ctrlcmn.cpp
  ${wxroot}/src/common/ctrlsub.cpp
  ${wxroot}/src/common/dcbase.cpp
  ${wxroot}/src/common/dcbufcmn.cpp
  ${wxroot}/src/common/dcgraph.cpp
  ${wxroot}/src/common/dcsvg.cpp
  ${wxroot}/src/common/dirctrlcmn.cpp
  ${wxroot}/src/common/dlgcmn.cpp
  ${wxroot}/src/common/dndcmn.cpp
  ${wxroot}/src/common/dobjcmn.cpp
  ${wxroot}/src/common/docmdi.cpp
  ${wxroot}/src/common/docview.cpp
  ${wxroot}/src/common/dpycmn.cpp
  ${wxroot}/src/common/dseldlg.cpp
  ${wxroot}/src/common/dummy.cpp
  ${wxroot}/src/common/effects.cpp
  ${wxroot}/src/common/event.cpp
  ${wxroot}/src/common/fddlgcmn.cpp
  ${wxroot}/src/common/filectrlcmn.cpp
  ${wxroot}/src/common/filehistorycmn.cpp
  ${wxroot}/src/common/filepickercmn.cpp
  ${wxroot}/src/common/fldlgcmn.cpp
  ${wxroot}/src/common/fontcmn.cpp
  ${wxroot}/src/common/fontdata.cpp
  ${wxroot}/src/common/fontenumcmn.cpp
  ${wxroot}/src/common/fontmap.cpp
  ${wxroot}/src/common/fontpickercmn.cpp
  ${wxroot}/src/common/fontutilcmn.cpp
  ${wxroot}/src/common/framecmn.cpp
  ${wxroot}/src/common/fs_mem.cpp
  ${wxroot}/src/common/gaugecmn.cpp
  ${wxroot}/src/common/gbsizer.cpp
  ${wxroot}/src/common/gdicmn.cpp
  ${wxroot}/src/common/geometry.cpp
  ${wxroot}/src/common/gifdecod.cpp
  ${wxroot}/src/common/graphcmn.cpp
  ${wxroot}/src/common/headercolcmn.cpp
  ${wxroot}/src/common/headerctrlcmn.cpp
  ${wxroot}/src/common/helpbase.cpp
  ${wxroot}/src/common/iconbndl.cpp
  ${wxroot}/src/common/imagall.cpp
  ${wxroot}/src/common/imagbmp.cpp
  ${wxroot}/src/common/image.cpp
  ${wxroot}/src/common/imagfill.cpp
  ${wxroot}/src/common/imaggif.cpp
  ${wxroot}/src/common/imagiff.cpp
  ${wxroot}/src/common/imagjpeg.cpp
  ${wxroot}/src/common/imagpcx.cpp
  ${wxroot}/src/common/imagpng.cpp
  ${wxroot}/src/common/imagpnm.cpp
  ${wxroot}/src/common/imagtga.cpp
  ${wxroot}/src/common/imagtiff.cpp
  ${wxroot}/src/common/imagxpm.cpp
  ${wxroot}/src/common/layout.cpp
  ${wxroot}/src/common/lboxcmn.cpp
  ${wxroot}/src/common/listctrlcmn.cpp
  ${wxroot}/src/common/markupparser.cpp
  ${wxroot}/src/common/matrix.cpp
  ${wxroot}/src/common/menucmn.cpp
  ${wxroot}/src/common/modalhook.cpp
  ${wxroot}/src/common/mousemanager.cpp
  ${wxroot}/src/common/msgout.cpp
  ${wxroot}/src/common/nbkbase.cpp
  ${wxroot}/src/common/overlaycmn.cpp
  ${wxroot}/src/common/ownerdrwcmn.cpp
  ${wxroot}/src/common/panelcmn.cpp
  ${wxroot}/src/common/paper.cpp
  ${wxroot}/src/common/persist.cpp
  ${wxroot}/src/common/pickerbase.cpp
  ${wxroot}/src/common/popupcmn.cpp
  ${wxroot}/src/common/preferencescmn.cpp
  ${wxroot}/src/common/prntbase.cpp
  ${wxroot}/src/common/quantize.cpp
  ${wxroot}/src/common/radiobtncmn.cpp
  ${wxroot}/src/common/radiocmn.cpp
  ${wxroot}/src/common/rearrangectrl.cpp
  ${wxroot}/src/common/rendcmn.cpp
  ${wxroot}/src/common/rgncmn.cpp
  ${wxroot}/src/common/scrolbarcmn.cpp
  ${wxroot}/src/common/settcmn.cpp
  ${wxroot}/src/common/sizer.cpp
  ${wxroot}/src/common/slidercmn.cpp
  ${wxroot}/src/common/spinbtncmn.cpp
  ${wxroot}/src/common/spinctrlcmn.cpp
  ${wxroot}/src/common/srchcmn.cpp
  ${wxroot}/src/common/statbar.cpp
  ${wxroot}/src/common/statbmpcmn.cpp
  ${wxroot}/src/common/statboxcmn.cpp
  ${wxroot}/src/common/statlinecmn.cpp
  ${wxroot}/src/common/stattextcmn.cpp
  ${wxroot}/src/common/stockitem.cpp
  ${wxroot}/src/common/tbarbase.cpp
  ${wxroot}/src/common/textcmn.cpp
  ${wxroot}/src/common/textentrycmn.cpp
  ${wxroot}/src/common/textmeasurecmn.cpp
  ${wxroot}/src/common/toplvcmn.cpp
  ${wxroot}/src/common/treebase.cpp
  ${wxroot}/src/common/uiactioncmn.cpp
  ${wxroot}/src/common/utilscmn.cpp
  ${wxroot}/src/common/valgen.cpp
  ${wxroot}/src/common/validate.cpp
  ${wxroot}/src/common/valnum.cpp
  ${wxroot}/src/common/valtext.cpp
  ${wxroot}/src/common/wincmn.cpp
  ${wxroot}/src/common/windowid.cpp
  ${wxroot}/src/common/wrapsizer.cpp
  ${wxroot}/src/xrc/xmlreshandler.cpp
  ${wxroot}/src/common/xpmdecod.cpp
  )
source_group("Common Sources" FILES ${Common_srcs})
list(APPEND ${lib_name}_libsrcs ${Common_srcs})
########################
# Generic Headers
set(Generic_hdrs
  ${wxroot}/include/wx/generic/accel.h
  ${wxroot}/include/wx/generic/busyinfo.h
  ${wxroot}/include/wx/generic/buttonbar.h
  ${wxroot}/include/wx/generic/choicdgg.h
  ${wxroot}/include/wx/generic/clrpickerg.h
  ${wxroot}/include/wx/generic/collheaderctrl.h
  ${wxroot}/include/wx/generic/collpaneg.h
  ${wxroot}/include/wx/generic/combo.h
  ${wxroot}/include/wx/generic/custombgwin.h
  ${wxroot}/include/wx/generic/dcpsg.h
  ${wxroot}/include/wx/generic/dirctrlg.h
  ${wxroot}/include/wx/generic/dragimgg.h
  ${wxroot}/include/wx/generic/filectrlg.h
  ${wxroot}/include/wx/generic/filepickerg.h
  ${wxroot}/include/wx/generic/fontpickerg.h
  ${wxroot}/include/wx/generic/headerctrlg.h
  ${wxroot}/include/wx/generic/infobar.h
  ${wxroot}/include/wx/generic/logg.h
  ${wxroot}/include/wx/generic/msgdlgg.h
  ${wxroot}/include/wx/generic/notebook.h
  ${wxroot}/include/wx/generic/numdlgg.h
  ${wxroot}/include/wx/generic/panelg.h
  ${wxroot}/include/wx/generic/printps.h
  ${wxroot}/include/wx/generic/prntdlgg.h
  ${wxroot}/include/wx/generic/progdlgg.h
  ${wxroot}/include/wx/generic/richmsgdlgg.h
  ${wxroot}/include/wx/generic/scrolwin.h
  ${wxroot}/include/wx/generic/spinctlg.h
  ${wxroot}/include/wx/generic/splitter.h
  ${wxroot}/include/wx/generic/srchctlg.h
  ${wxroot}/include/wx/generic/statbmpg.h
  ${wxroot}/include/wx/generic/stattextg.h
  ${wxroot}/include/wx/generic/textdlgg.h
  ${wxroot}/include/wx/generic/treectlg.h
  )
source_group("Generic Headers" FILES ${Generic_hdrs})
list(APPEND ${lib_name}_libsrcs ${Generic_hdrs})
########################
# Generic Sources
set(Generic_srcs
  ${wxroot}/src/generic/busyinfo.cpp
  ${wxroot}/src/generic/buttonbar.cpp
  ${wxroot}/src/generic/choicbkg.cpp
  ${wxroot}/src/generic/choicdgg.cpp
  ${wxroot}/src/generic/clrpickerg.cpp
  ${wxroot}/src/generic/collheaderctrlg.cpp
  ${wxroot}/src/generic/collpaneg.cpp
  ${wxroot}/src/generic/combog.cpp
  ${wxroot}/src/generic/dcpsg.cpp
  ${wxroot}/src/generic/dirctrlg.cpp
  ${wxroot}/src/generic/dragimgg.cpp
  ${wxroot}/src/generic/filectrlg.cpp
  ${wxroot}/src/generic/filepickerg.cpp
  ${wxroot}/src/generic/fontpickerg.cpp
  ${wxroot}/src/generic/graphicc.cpp
  ${wxroot}/src/generic/headerctrlg.cpp
  ${wxroot}/src/generic/infobar.cpp
  ${wxroot}/src/generic/listbkg.cpp
  ${wxroot}/src/generic/logg.cpp
  ${wxroot}/src/generic/markuptext.cpp
  ${wxroot}/src/generic/msgdlgg.cpp
  ${wxroot}/src/generic/numdlgg.cpp
  ${wxroot}/src/generic/preferencesg.cpp
  ${wxroot}/src/generic/printps.cpp
  ${wxroot}/src/generic/prntdlgg.cpp
  ${wxroot}/src/generic/progdlgg.cpp
  ${wxroot}/src/generic/renderg.cpp
  ${wxroot}/src/generic/richmsgdlgg.cpp
  ${wxroot}/src/generic/scrlwing.cpp
  ${wxroot}/src/generic/selstore.cpp
  ${wxroot}/src/generic/spinctlg.cpp
  ${wxroot}/src/generic/splitter.cpp
  ${wxroot}/src/generic/srchctlg.cpp
  ${wxroot}/src/generic/statbmpg.cpp
  ${wxroot}/src/generic/stattextg.cpp
  ${wxroot}/src/generic/statusbr.cpp
  ${wxroot}/src/generic/textdlgg.cpp
  ${wxroot}/src/generic/tipwin.cpp
  ${wxroot}/src/generic/toolbkg.cpp
  ${wxroot}/src/generic/treebkg.cpp
  ${wxroot}/src/generic/treectlg.cpp
  ${wxroot}/src/generic/vlbox.cpp
  ${wxroot}/src/generic/vscroll.cpp
  )
source_group("Generic Sources" FILES ${Generic_srcs})
list(APPEND ${lib_name}_libsrcs ${Generic_srcs})
########################
# MSW Headers
set(MSW_hdrs
  ${wxroot}/include/wx/msw/accel.h
  ${wxroot}/include/wx/msw/ole/access.h
  ${wxroot}/include/wx/msw/ole/activex.h
  ${wxroot}/include/wx/msw/anybutton.h
  ${wxroot}/include/wx/msw/app.h
  ${wxroot}/include/wx/msw/appprogress.h
  ${wxroot}/include/wx/msw/ole/automtn.h
  ${wxroot}/include/wx/msw/bitmap.h
  ${wxroot}/include/wx/msw/bmpbuttn.h
  ${wxroot}/include/wx/msw/brush.h
  ${wxroot}/include/wx/msw/button.h
  ${wxroot}/include/wx/msw/caret.h
  ${wxroot}/include/wx/msw/checkbox.h
  ${wxroot}/include/wx/msw/checklst.h
  ${wxroot}/include/wx/msw/choice.h
  ${wxroot}/include/wx/msw/clipbrd.h
  ${wxroot}/include/wx/msw/colordlg.h
  ${wxroot}/include/wx/msw/colour.h
  ${wxroot}/include/wx/msw/combo.h
  ${wxroot}/include/wx/msw/combobox.h
  ${wxroot}/include/wx/msw/control.h
  ${wxroot}/include/wx/msw/ctrlsub.h
  ${wxroot}/include/wx/msw/cursor.h
  ${wxroot}/include/wx/msw/custombgwin.h
  ${wxroot}/include/wx/msw/ole/dataform.h
  ${wxroot}/include/wx/msw/ole/dataobj.h
  ${wxroot}/include/wx/msw/ole/dataobj2.h
  ${wxroot}/include/wx/msw/dc.h
  ${wxroot}/include/wx/msw/dcclient.h
  ${wxroot}/include/wx/msw/dcmemory.h
  ${wxroot}/include/wx/msw/dcprint.h
  ${wxroot}/include/wx/msw/dcscreen.h
  ${wxroot}/include/wx/msw/dialog.h
  ${wxroot}/include/wx/msw/dib.h
  ${wxroot}/include/wx/msw/dirdlg.h
  ${wxroot}/include/wx/msw/dragimag.h
  ${wxroot}/include/wx/msw/ole/dropsrc.h
  ${wxroot}/include/wx/msw/ole/droptgt.h
  ${wxroot}/include/wx/msw/enhmeta.h
  ${wxroot}/include/wx/msw/evtloop.h
  ${wxroot}/include/wx/msw/fdrepdlg.h
  ${wxroot}/include/wx/msw/filedlg.h
  ${wxroot}/include/wx/msw/font.h
  ${wxroot}/include/wx/msw/fontdlg.h
  ${wxroot}/include/wx/msw/frame.h
  ${wxroot}/include/wx/msw/gauge.h
  ${wxroot}/include/wx/msw/gdiimage.h
  ${wxroot}/include/wx/msw/genrcdefs.h
  ${wxroot}/include/wx/msw/headerctrl.h
  ${wxroot}/include/wx/msw/helpchm.h
  ${wxroot}/include/wx/msw/helpwin.h
  ${wxroot}/include/wx/msw/htmlhelp.h
  ${wxroot}/include/wx/msw/icon.h
  ${wxroot}/include/wx/msw/imaglist.h
  ${wxroot}/include/wx/msw/iniconf.h
  ${wxroot}/include/wx/msw/init.h
  ${wxroot}/include/wx/msw/listbox.h
  ${wxroot}/include/wx/msw/listctrl.h
  ${wxroot}/include/wx/msw/mdi.h
  ${wxroot}/include/wx/msw/menu.h
  ${wxroot}/include/wx/msw/menuitem.h
  ${wxroot}/include/wx/msw/metafile.h
  ${wxroot}/include/wx/msw/minifram.h
  ${wxroot}/include/wx/msw/missing.h
  ${wxroot}/include/wx/msw/msgdlg.h
  ${wxroot}/include/wx/msw/msvcrt.h
  ${wxroot}/include/wx/msw/nonownedwnd.h
  ${wxroot}/include/wx/msw/notebook.h
  ${wxroot}/include/wx/msw/ole/oleutils.h
  ${wxroot}/include/wx/msw/ownerdrawnbutton.h
  ${wxroot}/include/wx/msw/ownerdrw.h
  ${wxroot}/include/wx/msw/palette.h
  ${wxroot}/include/wx/msw/panel.h
  ${wxroot}/include/wx/msw/pen.h
  ${wxroot}/include/wx/msw/popupwin.h
  ${wxroot}/include/wx/msw/printdlg.h
  ${wxroot}/include/wx/msw/printwin.h
  ${wxroot}/include/wx/msw/progdlg.h
  ${wxroot}/include/wx/msw/radiobox.h
  ${wxroot}/include/wx/msw/radiobut.h
  ${wxroot}/include/wx/msw/rcdefs.h
  ${wxroot}/include/wx/msw/region.h
  ${wxroot}/include/wx/msw/richmsgdlg.h
  ${wxroot}/include/wx/msw/ole/safearray.h
  ${wxroot}/include/wx/msw/scrolbar.h
  ${wxroot}/include/wx/msw/slider.h
  ${wxroot}/include/wx/msw/spinbutt.h
  ${wxroot}/include/wx/msw/spinctrl.h
  ${wxroot}/include/wx/msw/statbmp.h
  ${wxroot}/include/wx/msw/statbox.h
  ${wxroot}/include/wx/msw/statline.h
  ${wxroot}/include/wx/msw/stattext.h
  ${wxroot}/include/wx/msw/statusbar.h
  ${wxroot}/include/wx/msw/taskbarbutton.h
  ${wxroot}/include/wx/msw/textctrl.h
  ${wxroot}/include/wx/msw/textentry.h
  ${wxroot}/include/wx/msw/tglbtn.h
  ${wxroot}/include/wx/msw/toolbar.h
  ${wxroot}/include/wx/msw/tooltip.h
  ${wxroot}/include/wx/msw/toplevel.h
  ${wxroot}/include/wx/msw/treectrl.h
  ${wxroot}/include/wx/msw/rt/utils.h
  ${wxroot}/include/wx/msw/ole/uuid.h
  ${wxroot}/include/wx/msw/uxtheme.h
  ${wxroot}/include/wx/msw/uxthemep.h
  ${wxroot}/include/wx/msw/window.h
  )
source_group("MSW Headers" FILES ${MSW_hdrs})
list(APPEND ${lib_name}_libsrcs ${MSW_hdrs})
########################
# MSW Sources
set(MSW_srcs
  ${wxroot}/src/msw/accel.cpp
  ${wxroot}/src/msw/ole/access.cpp
  ${wxroot}/src/msw/ole/activex.cpp
  ${wxroot}/src/msw/anybutton.cpp
  ${wxroot}/src/msw/app.cpp
  ${wxroot}/src/msw/appprogress.cpp
  ${wxroot}/src/msw/artmsw.cpp
  ${wxroot}/src/msw/ole/automtn.cpp
  ${wxroot}/src/msw/bitmap.cpp
  ${wxroot}/src/msw/bmpbuttn.cpp
  ${wxroot}/src/msw/brush.cpp
  ${wxroot}/src/msw/button.cpp
  ${wxroot}/src/msw/caret.cpp
  ${wxroot}/src/msw/checkbox.cpp
  ${wxroot}/src/msw/checklst.cpp
  ${wxroot}/src/msw/choice.cpp
  ${wxroot}/src/msw/clipbrd.cpp
  ${wxroot}/src/msw/colordlg.cpp
  ${wxroot}/src/msw/colour.cpp
  ${wxroot}/src/msw/combo.cpp
  ${wxroot}/src/msw/combobox.cpp
  ${wxroot}/src/msw/control.cpp
  ${wxroot}/src/msw/cursor.cpp
  ${wxroot}/src/msw/data.cpp
  ${wxroot}/src/msw/ole/dataobj.cpp
  ${wxroot}/src/msw/dc.cpp
  ${wxroot}/src/msw/dcclient.cpp
  ${wxroot}/src/msw/dcmemory.cpp
  ${wxroot}/src/msw/dcprint.cpp
  ${wxroot}/src/msw/dcscreen.cpp
  ${wxroot}/src/msw/dialog.cpp
  ${wxroot}/src/msw/dialup.cpp
  ${wxroot}/src/msw/dib.cpp
  ${wxroot}/src/msw/dirdlg.cpp
  ${wxroot}/src/msw/display.cpp
  ${wxroot}/src/msw/dragimag.cpp
  ${wxroot}/src/msw/ole/dropsrc.cpp
  ${wxroot}/src/msw/ole/droptgt.cpp
  ${wxroot}/src/msw/enhmeta.cpp
  ${wxroot}/src/msw/evtloop.cpp
  ${wxroot}/src/msw/fdrepdlg.cpp
  ${wxroot}/src/msw/filedlg.cpp
  ${wxroot}/src/msw/font.cpp
  ${wxroot}/src/msw/fontdlg.cpp
  ${wxroot}/src/msw/fontenum.cpp
  ${wxroot}/src/msw/fontutil.cpp
  ${wxroot}/src/msw/frame.cpp
  ${wxroot}/src/msw/gauge.cpp
  ${wxroot}/src/msw/gdiimage.cpp
  ${wxroot}/src/msw/gdiobj.cpp
  ${wxroot}/src/msw/gdiplus.cpp
  ${wxroot}/src/msw/graphics.cpp
  ${wxroot}/src/msw/graphicsd2d.cpp
  ${wxroot}/src/msw/headerctrl.cpp
  ${wxroot}/src/msw/helpchm.cpp
  ${wxroot}/src/msw/helpwin.cpp
  ${wxroot}/src/msw/icon.cpp
  ${wxroot}/src/msw/imaglist.cpp
  ${wxroot}/src/msw/iniconf.cpp
  ${wxroot}/src/msw/listbox.cpp
  ${wxroot}/src/msw/listctrl.cpp
  ${wxroot}/src/msw/main.cpp
  ${wxroot}/src/msw/mdi.cpp
  ${wxroot}/src/msw/menu.cpp
  ${wxroot}/src/msw/menuitem.cpp
  ${wxroot}/src/msw/metafile.cpp
  ${wxroot}/src/msw/minifram.cpp
  ${wxroot}/src/msw/msgdlg.cpp
  ${wxroot}/src/msw/nativdlg.cpp
  ${wxroot}/src/msw/nativewin.cpp
  ${wxroot}/src/msw/nonownedwnd.cpp
  ${wxroot}/src/msw/notebook.cpp
  ${wxroot}/src/msw/ole/oleutils.cpp
  ${wxroot}/src/msw/ownerdrw.cpp
  ${wxroot}/src/msw/palette.cpp
  ${wxroot}/src/msw/panel.cpp
  ${wxroot}/src/msw/pen.cpp
  ${wxroot}/src/msw/popupwin.cpp
  ${wxroot}/src/msw/printdlg.cpp
  ${wxroot}/src/msw/printwin.cpp
  ${wxroot}/src/msw/progdlg.cpp
  ${wxroot}/src/msw/radiobox.cpp
  ${wxroot}/src/msw/radiobut.cpp
  ${wxroot}/src/msw/region.cpp
  ${wxroot}/src/msw/renderer.cpp
  ${wxroot}/src/msw/richmsgdlg.cpp
  ${wxroot}/src/msw/ole/safearray.cpp
  ${wxroot}/src/msw/scrolbar.cpp
  ${wxroot}/src/msw/settings.cpp
  ${wxroot}/src/msw/slider.cpp
  ${wxroot}/src/msw/spinbutt.cpp
  ${wxroot}/src/msw/spinctrl.cpp
  ${wxroot}/src/msw/statbmp.cpp
  ${wxroot}/src/msw/statbox.cpp
  ${wxroot}/src/msw/statline.cpp
  ${wxroot}/src/msw/stattext.cpp
  ${wxroot}/src/msw/statusbar.cpp
  ${wxroot}/src/msw/systhemectrl.cpp
  ${wxroot}/src/msw/taskbarbutton.cpp
  ${wxroot}/src/msw/textctrl.cpp
  ${wxroot}/src/msw/textentry.cpp
  ${wxroot}/src/msw/textmeasure.cpp
  ${wxroot}/src/msw/tglbtn.cpp
  ${wxroot}/src/msw/toolbar.cpp
  ${wxroot}/src/msw/tooltip.cpp
  ${wxroot}/src/msw/toplevel.cpp
  ${wxroot}/src/msw/treectrl.cpp
  ${wxroot}/src/msw/uiaction.cpp
  ${wxroot}/src/msw/utilsgui.cpp
  ${wxroot}/src/msw/rt/utilsrt.cpp
  ${wxroot}/src/msw/utilswin.cpp
  ${wxroot}/src/msw/ole/uuid.cpp
  ${wxroot}/src/msw/uxtheme.cpp
  #${wxroot}/src/msw/version.rc
  ${wxroot}/src/msw/volume.cpp
  ${wxroot}/src/msw/window.cpp
  )
source_group("MSW Sources" FILES ${MSW_srcs})
list(APPEND ${lib_name}_libsrcs ${MSW_srcs})
########################
# Setup Headers
set(Setup_hdrs
  ${wxroot}/include/wx/msw/setup.h
  )
source_group("Setup Headers" FILES ${Setup_hdrs})
list(APPEND ${lib_name}_libsrcs ${Setup_hdrs})
#######################################
# library
add_library(${lib_name} STATIC ${${lib_name}_libsrcs})
get_directory_property(global_includes INCLUDE_DIRECTORIES)
set_property(TARGET ${lib_name} PROPERTY
  INCLUDE_DIRECTORIES ${global_includes}
    ${wxroot}/src/jpeg
    ${wxroot}/src/tiff/libtiff
    ${wxroot}/src/png
    ${wxroot}/src/zlib
  )
set_property(TARGET ${lib_name} PROPERTY
  COMPILE_DEFINITIONS wxUSE_BASE=0
  )
set_wxtarget_properties(${lib_name})
